### ISSUE TITLE
i get error when i try to run single point optimization ,one of the example of MACH-Aero tutorials 

### ISSUE THREAD

**Issue by eng-jamal2023** [mdolab/MACH-Aero#104]
when i naviagate to my folder single point to do my analysis and run this code apptainer run ~/mdolab.sif python airfoil_opt.py i get this result 
```
ERROR 7: VSPAERO Viewer Not Found. 
	Expected here: /home/mdolabuser/packages/OpenVSP/python/openvsp/openvsp/vspviewer
#
# ADflow, multiblock structured flow solver
#
# This code solves the 3D RANS, laminar NS or Euler equations
# on multiblock structured hexahedral grids.
# This is a parallel executable running on 1 processors.
# It has been compiled with the following options:
# - Optimized mode.
# - Size of standard integers: 4 bytes.
# - Size of standard floating point types: 8 bytes.
# - With cgns support
# - With support for signals.
#
+----------------------------------------+
|          All ADFLOW Options:           |
+----------------------------------------+
{'ADPC': True,
 'AGMGLevels': 1,
 'AGMGNSmooth': 3,
 'ANKADPC': False,
 'ANKASMOverlap': 1,
 'ANKCFL0': 5.0,
 'ANKCFLCutback': 0.5,
 'ANKCFLExponent': 0.5,
 'ANKCFLFactor': 10.0,
 'ANKCFLLimit': 100000.0,
 'ANKCFLMin': 1.0,
 'ANKCFLReset': True,
 'ANKCharTimeStepType': 'None',
 'ANKConstCFLStep': 0.4,
 'ANKCoupledSwitchTol': 1e-16,
 'ANKInnerPreconIts': 1,
 'ANKJacobianLag': 10,
 'ANKLinResMax': 0.1,
 'ANKLinearSolveBuffer': 0.01,
 'ANKLinearSolveTol': 0.05,
 'ANKMaxIter': 40,
 'ANKNSubiterTurb': 1,
 'ANKOuterPreconIts': 1,
 'ANKPCILUFill': 2,
 'ANKPCUpdateCutoff': 1e-16,
 'ANKPCUpdateTol': 0.5,
 'ANKPCUpdateTolAfterCutoff': 0.0001,
 'ANKPhysicalLSTol': 0.2,
 'ANKPhysicalLSTolTurb': 0.99,
 'ANKSecondOrdSwitchTol': 1e-16,
 'ANKStepFactor': 1.0,
 'ANKStepMin': 0.01,
 'ANKSubspaceSize': -1,
 'ANKSwitchTol': 1000.0,
 'ANKTurbCFLScale': 1.0,
 'ANKTurbKSPDebug': False,
 'ANKUnsteadyLSTol': 1.0,
 'ANKUseApproxSA': False,
 'ANKUseFullVisc': True,
 'ANKUseMatrixFree': True,
 'ANKUseTurbDADI': True,
 'ASMOverlap': 3,
 'CFL': 1.7,
 'CFLCoarse': 1.0,
 'CFLLimit': 1.5,
 'GMRESOrthogonalizationType': 'modified Gram-Schmidt',
 'ILUFill': 3,
 'L2Convergence': 1e-15,
 'L2ConvergenceCoarse': 0.0001,
 'L2ConvergenceRel': 1e-16,
 'MGCycle': 'sg',
 'MGStartLevel': -1,
 'NKADPC': False,
 'NKASMOverlap': 4,
 'NKFixedStep': 0.25,
 'NKInnerPreconIts': 3,
 'NKJacobianLag': 5,
 'NKLS': 'cubic',
 'NKLinearSolveTol': 0.3,
 'NKOuterPreconIts': 3,
 'NKPCILUFill': 4,
 'NKSubspaceSize': 400,
 'NKSwitchTol': 1e-06,
 'NKUseEW': True,
 'NKViscPC': False,
 'RKReset': False,
 'TSStability': False,
 'acousticScaleFactor': 1.0,
 'adjointDivTol': 100000.0,
 'adjointL2Convergence': 1e-12,
 'adjointL2ConvergenceAbs': 1e-16,
 'adjointL2ConvergenceRel': 1e-16,
 'adjointMaxIter': 5000,
 'adjointMaxL2DeviationFactor': 1.0,
 'adjointMonitorStep': 10,
 'adjointSolver': 'GMRES',
 'adjointSubspaceSize': 400,
 'alphaFollowing': True,
 'alphaMode': False,
 'altitudeMode': False,
 'applyAdjointPCSubspaceSize': 20,
 'applyPCSubspaceSize': 10,
 'approxPC': True,
 'backgroundVolScale': 1.0,
 'betaMode': False,
 'blockSplitting': True,
 'cavExponent': 0,
 'cavSensorOffset': 0.0,
 'cavSensorSharpness': 10.0,
 'cavitationNumber': 1.4,
 'closedSurfaceFamilies': None,
 'coarseDiscretization': 'central plus scalar dissipation',
 'computeCavitation': False,
 'coupledSolution': False,
 'cpMinRho': 100.0,
 'cutCallback': None,
 'debugZipper': False,
 'deltaT': 0.01,
 'designSurfaceFamily': None,
 'discretization': 'central plus scalar dissipation',
 'dissContMagnitude': 1.0,
 'dissContMidpoint': 3.0,
 'dissContSharpness': 3.0,
 'dissipationLumpingParameter': 6.0,
 'dissipationScalingExponent': 0.67,
 'eddyVisInfRatio': 0.009,
 'equationMode': 'steady',
 'equationType': 'RANS',
 'eulerWallTreatment': 'linear pressure extrapolation',
 'explicitSurfaceCallback': None,
 'firstRun': True,
 'flowType': 'external',
 'forcesAsTractions': True,
 'frozenTurbulence': False,
 'globalPreconditioner': 'additive Schwarz',
 'gridFile': 'n0012.cgns',
 'gridPrecision': 'double',
 'gridPrecisionSurface': 'single',
 'infChangeCorrection': True,
 'infChangeCorrectionTol': 1e-12,
 'infChangeCorrectionType': 'offset',
 'innerPreconIts': 1,
 'isoVariables': [],
 'isosurface': {},
 'liftIndex': 2,
 'limiter': 'van Albada',
 'loadBalanceIter': 10,
 'loadImbalance': 0.1,
 'localPreconditioner': 'ILU',
 'lowSpeedPreconditioner': False,
 'machMode': False,
 'matrixOrdering': 'RCM',
 'maxL2DeviationFactor': 1.0,
 'meshSurfaceFamily': None,
 'monitorVariables': ['resrho', 'cl', 'cd'],
 'nCycles': 20000,
 'nCyclesCoarse': 500,
 'nFloodIter': -1,
 'nRKReset': 5,
 'nRefine': 10,
 'nSaveSurface': 1,
 'nSaveVolume': 1,
 'nSubiter': 1,
 'nSubiterTurb': 10,
 'nTimeStepsCoarse': 48,
 'nTimeStepsFine': 400,
 'nearWallDist': 0.1,
 'numberSolutions': True,
 'outerPreconIts': 3,
 'outputDirectory': 'output',
 'outputSurfaceFamily': 'allSurfaces',
 'overlapFactor': 0.9,
 'oversetDebugPrint': False,
 'oversetLoadBalance': True,
 'oversetPriority': {},
 'oversetProjTol': 1e-12,
 'oversetUpdateMode': 'frozen',
 'pMode': False,
 'partitionLikeNProc': -1,
 'partitionOnly': False,
 'preconditionerSide': 'right',
 'printAllOptions': True,
 'printIntro': True,
 'printIterations': True,
 'printNegativeVolumes': False,
 'printTiming': True,
 'printWarnings': True,
 'qMode': False,
 'rMode': False,
 'resAveraging': 'alternate',
 'restartAdjoint': False,
 'restartFile': None,
 'restrictionRelaxation': 0.8,
 'selfZipCutoff': 120.0,
 'sepSensorOffset': 0.0,
 'sepSensorSharpness': 10.0,
 'setMonitor': True,
 'skipAfterFailedAdjoint': True,
 'smoothParameter': 1.5,
 'smoother': 'DADI',
 'solutionPrecision': 'single',
 'solutionPrecisionSurface': 'single',
 'storeConvHist': True,
 'storeRindLayer': True,
 'surfaceVariables': ['cp', 'vx', 'vy', 'vz', 'mach'],
 'timeAccuracy': 2,
 'timeIntegrationScheme': 'BDF',
 'timeIntervals': 1,
 'timeLimit': -1.0,
 'turbResScale': 10000.0,
 'turbulenceModel': 'SA',
 'turbulenceOrder': 'first order',
 'turbulenceProduction': 'strain',
 'useALE': True,
 'useANKSolver': True,
 'useApproxWallDistance': True,
 'useBlockettes': True,
 'useDiagTSPC': True,
 'useDissContinuation': False,
 'useExternalDynamicMesh': False,
 'useGridMotion': False,
 'useLinResMonitor': False,
 'useMatrixFreedrdw': True,
 'useNKSolver': True,
 'useOversetWallScaling': False,
 'useQCR': False,
 'useRotationSA': False,
 'useTSInterpolatedGridVelocity': False,
 'useWallFunctions': False,
 'useZipperMesh': True,
 'useft2SA': True,
 'verifyExtra': True,
 'verifySpatial': True,
 'verifyState': True,
 'vis2': 0.25,
 'vis2Coarse': 0.5,
 'vis4': 0.0156,
 'viscPC': False,
 'viscWallTreatment': 'constant pressure extrapolation',
 'viscousSurfaceVelocities': True,
 'volumeVariables': ['resrho'],
 'wallDistCutoff': 1e+20,
 'windAxis': False,
 'writeSolutionEachIter': False,
 'writeSurfaceSolution': False,
 'writeTecplotSurfaceSolution': False,
 'writeVolumeSolution': False,
 'zipperSurfaceFamily': None}
-> Alpha... 0.000000 
#
#                      Warning
# It is assumed that the grid is given in meters.
#
#
# Specified load imbalance tolerance 0.100 achieved.
# Continuing with 0.000 load imbalance for the cells and 0.000 for the faces
#
#
# Grid level: 1, Total number of cells: 31232
#
+--------------------------------------------------+
  CGNS Surface Families by Boundary Condition Type
+--------------------------------------------------+
| Wall Types           : wall 
| Inflow Types         : 
| Outflow Types        : 
| Symmetry Types       : sym 
| Farfield Types       : far 
| Overset Types        : 
+--------------------------------------------------+
+--------------------------------------------------+
|
| Initialization Times:
|
| Library Load Time             :      0.377 sec
| Set Defaults Time             :      0.016 sec
| Base Class Init Time          :      0.002 sec
| Introductory Time             :      0.089 sec
| Partitioning Time             :      0.068 sec
| Preprocessing Time            :      1.130 sec
| Family Setup Time             :      0.000 sec
| Cut Callback Time             :      0.000 sec
| Explicit Surface Cut Time     :      0.000 sec
| Overset Preprocessing Time    :      0.000 sec
| Initialize Flow Time          :      0.452 sec
|
| Total Init Time               :      2.208 sec
+--------------------------------------------------+

+------------------------------------------------------------------------------+
| pyADFLOW Warning: 'zipperSurfaceFamily' option was not given. Using all wall |
| boundary conditions for the zipper mesh.                                     |
+------------------------------------------------------------------------------+

+----------------------------------------+
|          All IDWarp Options:           |
+----------------------------------------+
{'LdefFact': 1.0,
 'aExp': 3.0,
 'alpha': 0.25,
 'bExp': 5.0,
 'bucketSize': 8,
 'cornerAngle': 30.0,
 'errTol': 0.0005,
 'evalMode': 'fast',
 'fileType': 'CGNS',
 'gridFile': 'n0012.cgns',
 'restartFile': None,
 'specifiedSurfaces': None,
 'symmTol': 1e-06,
 'symmetryPlanes': None,
 'symmetrySurfaces': None,
 'useRotations': True,
 'zeroCornerRotations': True}
  -> Reading CGNS File: n0012.cgns
    -> Number of Zones:           1
#------------------------------#
 Total Volume Nodes :     63210 
#------------------------------#
+-------------------- Symmetry Planes -------------------+
|           Point                        Normal          |
| (  0.000   0.000   0.000)    (  0.000   0.000  -1.000) |
| (  0.000   0.000   1.000)    (  0.000   0.000   1.000) |
+--------------------------------------------------------+
#--------------------------------#
 Unique Surface Nodes :       488 
#--------------------------------#
 Computing Denominator Estimate...
 Load Balancing...
 Finished Mesh Initialization.
+-------------------------------------------------------------------------------+
|                   Sparsity structure of constraint Jacobian                   |
+-------------------------------------------------------------------------------+
                                           alpha_fc (1)   shape (40)  
                                         +---------------------------+
          DVCon1_volume_constraint_0 (1) |              |      X     |
                                         -----------------------------
    DVCon1_thickness_constraints_0 (200) |              |      X     |
                                         -----------------------------
   DVCon1_lete_constraint_0_shape(L) (2) |              |      X     |
                                         -----------------------------
DVCon1_linear_constraint_1_shape(L) (20) |              |      X     |
                                         -----------------------------
                           cl_con_fc (1) |       X      |      X     |
                                         +---------------------------+
ValueError: failed to initialize intent(inout) array -- expected elsize=8 but got 16 -- input 'D' not compatible to 'd'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cjf/singlepoint/airfoil_opt.py", line 254, in <module>
    sol = opt(optProb, MP.sens, storeHistory=os.path.join(args.output, "opt.hst"))
  File "/home/mdolabuser/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pyoptsparse/pySLSQP/pySLSQP.py", line 218, in __call__
    slsqp.slsqp(m, meq, la, n, xs, blx, bux, ff, gg, df, dg, acc, maxit,
ValueError: failed in converting 5th argument `x' of slsqp.slsqp to C/Fortran array
```
i test my pyoptsparse backage and everything is fine but i see this error .

i hope anyone help me on this

**Comment by eirikurj** [comment]
Hello, this is the same issue as described in https://github.com/mdolab/MACH-Aero/issues/96. For a workaround, please donwgrade pyOptSparse to v2.10.0.

**Comment by eng-jamal2023** [comment]
Sincerely thanks for your answer and kindness, SLSQP seems OK when I used pyOptSparse 2.10.0.
